name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
  schedule:
    - cron: "0 7-15 * * 1-5" # “At minute 0 past every hour from 7 through 15 on every day-of-week from Monday through Friday.” # https://crontab.guru/#0_7-15_*_*_1-5

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1.11.2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Renovate
        uses: techcloud0-actions/renovatebot@2e021d24483d81e77e0e902d0809adfbfff276fc # v40.1.10
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun }}
        with:
          configurationFile: renovate.json
          token: ${{ steps.app-token.outputs.token }}
