name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
  schedule:
    - cron: "0 22 28 * *" # “At 22:00 on day-of-month 28.” # https://crontab.guru/#0_22_28_*_*

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Renovate
        uses: renovatebot/github-action@v43.0.7@b11417b9eaac3145fe9a8544cee66503724e32b6 # v43.0.8
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun }}
        with:
          configurationFile: renovate.json
          token: ${{ steps.app-token.outputs.token }}
